version: '2'

services: 
  php: 
    build:
      context: ./docker/php
    volumes:
      - ".docker/myapp:/var/www/"
    ports:
      - "8000:80"
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    image: adminer
    restart: always
    ports:
      - "6080:8080"